#pragma once
#ifndef __ENEMY_BULLET_ANIMATION_STATE__
#define __ENEMY_BULLET_ANIMATION_STATE__

enum EnemyBulletAnimationState
{
	ENEMY_BULLET_MOVE_RIGHT,
	ENEMY_BULLET_MOVE_LEFT,
	ENEMY_BULLET_CRASH_RIGHT,
	ENEMY_BULLET_CRASH_LEFT,
	NUM_OF_ENEMYBULLET_ANIMATION_STATES
};

#endif