#pragma once
#ifndef __GAME_OBJECT_TYPE__
#define __GAME_OBJECT_TYPE__
enum GameObjectType {
	NONE = -1,
	SHIP,
	TARGET,
	PLAYER,
	PLANE,
	ENEMY,
	P_BULLET,
	E_BULLET,
	OBSTACLE,
	BACKGROUND,
	START_BUTTON,
	RESTART_BUTTON,
	PAUSE_BUTTON,
	CONTINUE_BUTTON,
	NEXT_BUTTON,
	NUM_OF_TYPES
};
#endif /* defined (__GAME_OBJECT_TYPE__) */